### ISSUE TITLE
Use NineOldAndroids to add animations to old APIs

### ISSUE THREAD

**Issue by EmmanuelMess** [roughike/SwipeSelector#18]
[NineOldAndroids](https://github.com/JakeWharton/NineOldAndroids) lets you use ..."the Honeycomb (Android 3.0) animation API on all versions of the platform back to 1.0!".

**Comment by roughike** [comment]
I know about NineOldAndroids already.

For me it makes no sense to include a whole library just for supporting lower APIs, as the Play Store coverage should already be 100% and an external animation library isn't mandatory for that anyway.

**Comment by EmmanuelMess** [comment]
@roughike API 8 has no animation I think NineOldAndroids could be used to make the SwipeSelector look the same in all supported APIs (not to add more).
