### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by oZBo** [roughike/SwipeSelector#3]
Hi!

Is there some opportunity to change font for my custom?

Thanks for reply!

**Comment by roughike** [comment]
Use [Calligraphy](https://github.com/chrisjenx/Calligraphy). The SwipeSelector library should just get nicely along with it.

**Comment by roughike** [comment]
As it's not such a big of a deal to add this feature, I'll just implement it in the next version.

**Comment by roughike** [comment]
It's now possible. For sample use, please refer to the [Customization section](https://github.com/roughike/SwipeSelector#customization) in the README.

**Comment by oZBo** [comment]
Well Done! Thanks for your reply! Sorry for late answer.
