### ISSUE TITLE
No resource identifier found for attribute...  error

### ISSUE THREAD

**Issue by usergoodvery** [roughike/SwipeSelector#31]
Hi,

Android 7.1.1. api25 I am unable to set any of the custom attributes, as I get "no resource found.." as per the example below:
`No resource identifier found for attribute 'swipe_unselectedItemTitle' in package '...'`

My root attribute has:
 ```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
```
and all other custom attributes work fine.

I also tried 
`xmlns:app="http://schemas.android.com/apk/lib/com.roughike.swipeselector"`

**Comment by justrelax19** [comment]
Just check the gradle of Swipe selector with your gradle.
