### ISSUE TITLE
Is it support image selector?

### ISSUE THREAD

**Issue by onexuan** [roughike/SwipeSelector#4]
Is it support image selector?

**Comment by roughike** [comment]
I'm not sure what you mean, could you be more specific? Do you want to have images to the left of the title and description or something else?

**Comment by EmmanuelMess** [comment]
What should be done then?  Images to the left of the title and description or image instead of description or what? If it has no solution or meaning, this issue should be closed (no point in having an unsolvable issue).

**Comment by onexuan** [comment]
Yes. image instead of text

2016-03-02 12:29 GMT+08:00 Emmanuel notifications@github.com:

**Comment by EmmanuelMess** [comment]
@onexuan Should solve it: [Added the possibility of having an image instead of title](https://github.com/EmmanuelMess/SwipeSelector/commit/2e9b6ae7ac3cfd727eec29bcc806eb0e92edbcae) but I can't have two pull requests open in the same project at the same time.

**Comment by roughike** [comment]
@EmmanuelMess
Will review both this weekend and merge if all is OK. Been a busy week.

**Comment by onexuan** [comment]
You can close this issue, just do you want.

2016-03-05 7:02 GMT+08:00 Iiro Krankka notifications@github.com:

**Comment by moderateepheezy** [comment]
@roughike can i have this
"images to the left of the title "
